config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users do
    member do
      get 'to_authenticate'
      get 'to_revoke'
    end
  end

  get 'register', to: 'users#new', as: 'register'

  root 'pages#home'

  get 'pages/profile'

  get 'calendar', to: 'pages#calendar', as: 'calendar'

  get 'pages/tasks'

  get 'files', to: 'pages#files', as: 'files'

  get 'g/:string_id', to: 'groups#show_by_string_id', as:'group_string'
  post 'groups/search', to: 'groups#search', as: 'groups_search'
  resources :groups do
    resources :memberships, only: [:index, :create, :destroy, :update]
    post 'memberships/search', to: 'memberships#search', as: 'memberships_search'
    post 'memberships/add_user/:user_id', to: 'memberships#add_user', as: 'memberships_add'
    resources :categories, path: 'c' do
      resources :tasks
      resource :text_page, only: [:create, :new, :show, :update, :edit]
      get 'text_page/to_authenticate', to: 'text_pages#to_authenticate', as: 'text_page_auth'
      resources :contacts
      resource :display
      get 'display/to_authenticate', to: 'displays#to_authenticate', as: 'display_auth'
      resource :calendar, only: [:create, :new, :show, :update, :edit]
      resources :events
      get 'calendar/to_authenticate', to: 'calendars#to_authenticate', as: 'calendar_auth'
      post 'calendar/show_period', to: 'calendars#show_period', as: 'calendar_period'
      get 'events/google_edit/:id', to: 'events#google_edit', as: 'edit_google_event'

      get 'events/google/:id', to: 'events#google_show', as: 'google_event'
      post 'events/google/:id', to: 'events#google_update'
      delete 'events/google/:id', to: 'events#google_destroy'
      post 'events/index_period', to: 'events#index_period', as: 'events_period'
      post 'events/export_event/:id', to: 'events#export_event', as: 'export_event'
      post 'events/export_all_events', to: 'events#export_all_events', as: 'export_all_events'
    end
    post '/categories_save_order', to: 'categories#saveOrder', as: 'categories_save_order'
  end

  post '/join_group/:id', to: 'groups#join', as: 'join_group'

  get '/auth/:provider/callback', to: 'sessions#auth_callback', as: 'auth_callback'
  post 'register_with_google', to: 'sessions#register_with_google', as: 'register_with_google'
  post 'login_with_google', to: 'sessions#login_with_google', as: 'login_with_google'

end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id             :integer          not null, primary key
#  name           :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  members_public :boolean          default(TRUE)
#  string_id      :string
#  description    :text
#

class Group < ActiveRecord::Base
  # associations
  has_many :categories, dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships
  has_many :tasks, through: :categories
  has_many :task_assignments, through: :tasks
  has_many :calendars, through: :categories
  has_many :events, through: :calendars
  has_many :text_pages, through: :categories
  has_many :contacts, through: :categories
  # validations
  validates :name,
    presence: true
  validates :string_id,
    uniqueness: { case_sensitive: false },
    format: { with: /\A[A-Za-z0-9_-]+\Z/, message: "only allows letters, digits, hyphens and underscores"}


end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy, :join]
  before_action :set_auth, only:[:show, :edit, :update, :destroy]
  before_action :check_edit_auth, only: [:edit, :update, :destroy]
  before_action :check_logged_in, only:[:new, :create, :join]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.limit(10).all
  end

  def show_by_string_id
    @group=Group.find_by(string_id: params[:string_id].downcase)
    if @group
      redirect_to @group
    else
      redirect_to groups_path
    end
  end

  def search
    @groups = Group.where('LOWER(name) LIKE ?',"%#{params.require(:search)[:input]}%".downcase).order("LENGTH(name) ASC").limit(10)
    respond_to do |format|
      format.js{}
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    if @authorised_member
      @categories=@group.categories
      @members=@group.memberships
      @unapproved=@members.where(approved:false)
      @overdue=@group.tasks.where(done: false).where("deadline < ?",Date.today).order('deadline ASC').limit(5)
      @tasks=@group.tasks.where(done: false).where("deadline >= ?",Date.today).order("deadline ASC").limit(5)
      @events=@group.events.includes(:calendar).where('"end" >= ?',Time.now).order("start").where('"start" < ?',Time.now + 7.days).order("start ASC").limit(5).collect{|event|
        {start:event.start, google:false, event:event, category: event.calendar.category_id, time_zone: event.calendar.time_zone}}
      @group.calendars.each do |cal|
        next unless cal.google_calendar_id && cal.google_calendar_id.length>0
        begin
          token = cal.google_account.fresh_token
          calendar_client = Signet::OAuth2::Client.new(access_token: token)
          calendar_service = Google::Apis::CalendarV3::CalendarService.new
          calendar_service.authorization = calendar_client
          result= calendar_service.list_events(cal.google_calendar_id, single_events: true, max_results: 5,
            order_by: "startTime",time_max: (Time.now + 7.days).to_datetime.rfc3339,
            time_min: Time.now.to_datetime.rfc3339)
          @events.concat(result.items.collect{|event|{start: event.start.date_time,google: true, event:event, category: cal.category_id, time_zone:cal.time_zone}})
        rescue
        end
      end
      @events.sort!{
        |x,y| x[:start]<=>y[:start]
      }
      @events=@events.first(5)
      @text_pages=@group.text_pages
    end
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        @group.memberships.create(user_id: current_user.id, approved: true)
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /join_group/1
  def join
    @membership=@group.memberships.new(user_id: current_user.id, approved: false)
    if @membership.save
      flash[:notice] = "The request has been sent."
      redirect_to @group
    else
      flash[:error] = @membership.errors.full_messages
      redirect_to groups_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    def set_auth
      @authorised_member= is_user_of_group?(@group)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :members_public,:description,:string_id)
    end

    #checks if user if a member of the group
    def check_edit_auth
      unless logged_in?
        flash[:notice] = 'Log in as a member of the group.'
        redirect_to login_url
        return
      end
      unless @authorised_member
        flash[:notice] = 'Join the group and wait for your request to be accepted!'
        redirect_to groups_path
        return
      end
    end

    def check_logged_in
      unless logged_in?
        flash[:notice] = 'Please log in first.'
        redirect_to login_url
      end
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
  # approved member
  def is_user_of_group?(group)
    logged_in? && !Membership.where(user_id: current_user.id, group_id: group.id, approved: true).empty?
  end

  # not approved member
  def is_a_not_yet_approved_member_of_group?(group)
    logged_in? && !Membership.where(user_id: current_user.id, group_id: group.id, approved: false).empty?
  end

  def is_a_member_of_group?(group)
    logged_in? && !Membership.where(user_id: current_user.id, group_id: group.id).empty?
  end

  # returns array of hash of category name and associated path
  def get_categories_and_path(group)
    categories = if is_user_of_group?(group)
      group.categories.order(:order_no)
    else
      group.categories.is_public.order(:order_no)
    end
    array =[]
    categories.each do |cat|
      array.push({name: cat.name, path: [group,cat]}) if cat.id
    end
    #logger.info array.size.to_s + "number of element(s)\n"
    return array
  end

  def category_edit_auth_redirect(group,category)
    flash[:notice] = "Join the group to make a change!"
    redirect_to [group,category]
  end

  def check_category_view_auth(group,category)
    unless category.is_public
      flash[:notice] = "Join the group to see more!"
      redirect_to group
    end
  end

end

app/views/groups/_cards.html.erb
<div class="row card-grid" >
  <% @groups.each do |group| %>
    <div class="col s12 m6 grid-item">
      <div class="card group-card">
        <div class="card-content">
          <span class="card-title"><%=link_to "#{group.name}", group%></span>
          <p><%=group.description%></p>
        </div>
        <div class="card-action">
          <%=link_to "<i class='material-icons'>info</i>".html_safe, group,
            data: {position:"bottom", delay:"50",tooltip:"View Group"}, class:"tooltipped" %>
          <%if is_a_member_of_group?(group)%>
            <%if is_user_of_group?(group)%>
              <a class='tooltipped' data-position="bottom" data-delay="50" data-tooltip="Official Member"><i class='material-icons'>person</i></a>
            <%else%>
              <a class='tooltipped' data-position="bottom" data-delay="50" data-tooltip="Not approved yet :("><i class='material-icons'>person_outline</i></a>
            <%end%>
            <%=link_to "<i class='material-icons'>remove_circle</i>".html_safe, [group, group.memberships.find_by(user_id: current_user.id)], method: :delete,
            data: { confirm: "Leave #{group.name}?",position:"bottom", delay:"50",tooltip:"Leave Group"}, class:"tooltipped" %>

          <%elsif logged_in?%>
            <%=link_to "<i class='material-icons'>person_add</i>".html_safe,
              join_group_path(group.id), method: :post,class:"tooltipped", data:{position:"bottom", delay:"50",tooltip:"Join Group"}  %>
          <%end%>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/groups/_dashboard.html.erb
<div class="row dashboard-grid">
  <!-- group info card -->
  <div class="col s12 m6 grid-item">
    <div class="card group-info">
      <div class="card-content">
        <span class="card-title"><%=@group.name%></span>
        <p><%=@group.description%><br>
        <%=link_to group_string_url(@group.string_id),group_string_path(@group.string_id)%><br>
        Member List is <%="not "unless @group.members_public%>public.</p>
      </div>
    </div>
  </div>
  <% if @authorised_member%>
    <!-- members -->
    <div class="col s12 m6 grid-item">
      <div class="card dash-members">
        <div class="card-content">
          <span class="card-title">Members</span>
          <table>
            <tr class='members-row'>
              <td>Total no. of members</td>
              <td><%=@members.size%></td>
            </tr>
            <tr class='members-row'>
              <td>No. of unapproved members</td>
              <td><%=@unapproved.size%></td>
            </tr>
          </table>
        </div>
        <div class="card-action">
          <%=link_to '<i class="material-icons">list</i>'.html_safe, group_memberships_path(@group),
          data: {position:"bottom", delay:"50",tooltip:"View List"}, class:"tooltipped"%>
        </div>
      </div>
    </div>

    <!-- overdue tasks -->
    <div class="col s12 m6 grid-item">
      <div class="card dash-overdue">
        <div class="card-content">
          <span class="card-title">Overdue Tasks</span>
          <%if @overdue.empty?%>
            <p>No overdue tasks.</p>
          <%else%>
            <table class='highlight'>
              <%@overdue.each do |task|%>
                <tr>
                  <td><%=link_to task.name, group_category_task_path(@group,task.category_id,task)%></td>
                  <td><%=task.deadline.strftime('%e %b %4Y')%></td>
                </tr>
              <%end%>
            </table>
          <%end%>
        </div>
      </div>
    </div>

    <!-- events -->
    <div class="col s12 m6 grid-item">
      <div class="card dash-events">
        <div class="card-content">
          <span class="card-title">Upcoming Events</span>
          <%if @events.empty?%>
            <p>No upcoming events.</p>
          <%else%>
            <table class='highlight'>
              <%@events.each do |hash|%>
                <tr>
                  <%if hash[:google]%>
                    <td><%=link_to hash[:event].summary, group_category_google_event_path(@group,hash[:category],hash[:event].id)%></td>
                  <%else%>
                    <td><%=link_to hash[:event].summary, group_category_event_path(@group,hash[:category],hash[:event])%></td>
                  <%end%>
                  <td><%=hash[:start].to_time.in_time_zone(hash[:time_zone]).strftime('%e %B %4Y %R')%></td>
                </tr>
              <%end%>
            </table>
          <%end%>
        </div>
      </div>
    </div>

    <!-- tasks -->
    <div class="col s12 m6 grid-item">
      <div class="card dash-tasks">
        <div class="card-content">
          <span class="card-title">Upcoming Tasks</span>
          <%if @tasks.empty?%>
            <p>No upcoming tasks.</p>
          <%else%>
            <table class='highlight'>
              <%@tasks.each do |task|%>
                <tr>
                  <td><%=link_to task.name, group_category_task_path(@group,task.category_id,task)%></td>
                  <td><%=task.deadline.strftime('%e %b %4Y')%></td>
                </tr>
              <%end%>
            </table>
          <%end%>
        </div>
      </div>
    </div>

    <!-- text pages -->
    <div class="col s12 m6 grid-item">
      <div class="card dash-text-pages">
        <div class="card-content">
          <span class="card-title">Text Pages</span>
          <%if @text_pages.empty?%>
            <p>No text pages.</p>
          <%else%>
            <table class='highlight'>
              <thead><th>Title</th><th>Loading from Google</th></thead>
              <%@text_pages.each do |page|%>
                <tr>
                  <td><%=link_to page.title, group_category_text_page_path(@group,page.category_id)%></td>
                  <td><%=page.load_from_google==true%></td>
                </tr>
              <%end%>
            </table>
          <%end%>
        </div>
      </div>
    </div>

    <!-- categories -->
    <div class="col s12 m6 grid-item">
      <div class="card dash-categories">
        <div class="card-content">
          <span class="card-title">Categories</span>
          <%if @categories.empty?%>
            <p>No categories.</p>
          <%else%>
            <table class='highlight'>
              <thead><th>Name</th><th>Public</th></thead>
              <%@categories.each do |category|%>
                <tr>
                  <td><%=link_to category.name, group_category_path(@group,category)%></td>
                  <td><%=category.is_public==true%></td>
                </tr>
              <%end%>
            </table>
          <%end%>
        </div>
        <div class="card-action">
          <%=link_to '<i class="material-icons">list</i>'.html_safe, group_categories_path(@group),
          data: {position:"bottom", delay:"50",tooltip:"View List"}, class:"tooltipped"%>
        </div>
      </div>
    </div>

  <%end%>
</div>

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div class="col s12">
      <div class="alert">
        <p>The form contains <%= pluralize(@group.errors.count, "error") %>.</p>
      </div>
      <ul class='alert'>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field col s12">
    <%= f.text_field :name%>
    <%= f.label :name %>
  </div>
  <div class="input-field col s12">
    <%= f.text_field :string_id%>
    <%= f.label :string_id, "Group ID (#{group_string_url('group_id')})" %>
  </div>

  <div class="input-field col s12">
    <%= f.text_area :description, class: 'materialize-textarea'%>
    <%= f.label :description %>
  </div>
  <div class="input-field col s12">
    <%= f.check_box :members_public%>
    <%= f.label :members_public, "Set member list to be public"%>
  </div>
  <div class="actions col s12">
    <p><br><button class="btn-large waves-effect waves-light" type="submit" name="action">Submit
      <i class="material-icons right">send</i>
    </button></p>
  </div>
<% end %>

app/views/groups/edit.html.erb
<% provide(:title, "Update #{@group.name}") %>
<div class="row">
  <div class="col s12">
    <h1>Update <%=@group.name%></h1>
  </div>
</div>

<div class="row">
  <div class="col s12 m9">
    <%= render 'form' %>
  </div>
</div>

app/views/groups/index.html.erb
<% provide(:title, 'Groups') %>
<div class="row">
  <div class ="col s12">
    <h1>Groups</h1>
  </div>
</div>
<div class="row">
  <div class='col s12'>
    <%= link_to '<i class="material-icons left">add</i>New Group'.html_safe, new_group_path , class: "btn waves-effect waves-light red"%>
  </div>
</div>
<div class="row">
  <div>
    <%=form_for(:search, url: groups_search_path(@group),remote: true,  html: {id: "groups_search_form" }) do |f|%>
      <div class='input-field col s12'>
        <%=f.text_field :input, class:'groups-search' %>
        <%=f.label :input, "Search"%>
      </div>
    <%end%>
  </div>
</div>
<div id ='groups_div'>
  <%= render 'cards'%>
</div>

app/views/groups/new.html.erb
<% provide(:title, 'New Group') %>
<div class="row">
  <div class="col s12">
    <h1>New Group</h1>
  </div>
</div>

<div class="row">
  <div class="col s12 m9">
    <%= render 'form' %>
  </div>
</div>

app/views/groups/search.js.erb
$("#groups_div").html("<%= escape_javascript(render 'cards') %>");
$('.card-grid').isotope({
  itemSelector: '.grid-item',
  percentPosition: true
});

app/views/groups/show.html.erb
<% provide(:title, @group.name) %>
<div class="row">
  <div class="col s12">
      <h1><%=@group.name%></h1>
    </div>
</div>

<div class="row">
  <div class="col s12">

    <%if @authorised_member %>
      <%= link_to "<i class='material-icons'>mode_edit</i>".html_safe, edit_group_path(@group),
      class: "btn waves-effect waves-light tooltipped", data: {position:"bottom", delay:"50",tooltip:"Update"}%>
    <%end%>
    <%if is_a_member_of_group?(@group)%>
      <%=link_to "<i class='material-icons'>remove_circle</i>".html_safe, [@group, @group.memberships.find_by(user_id: current_user.id)], method: :delete,
        data: { confirm: "Leave #{@group.name}?",position:"bottom", delay:"50",tooltip:"Leave Group"}, class:"btn waves-effect waves-light tooltipped red" %>
    <%elsif logged_in?%>
      <%=link_to "<i class='material-icons'>person_add</i>".html_safe,
        join_group_path(@group), method: :post,class:"btn waves-effect waves-light tooltipped", data:{position:"bottom", delay:"50",tooltip:"Join Group"}  %>
    <%end%>

  </div>
</div>
<div id='dashboard_div'>
  <%= render 'dashboard'%>
</div>