config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users do
    member do
      get 'to_authenticate'
      get 'to_revoke'
    end
  end

  get 'register', to: 'users#new', as: 'register'

  root 'pages#home'

  get 'pages/profile'

  get 'calendar', to: 'pages#calendar', as: 'calendar'

  get 'pages/tasks'

  get 'files', to: 'pages#files', as: 'files'

  get 'g/:string_id', to: 'groups#show_by_string_id', as:'group_string'
  post 'groups/search', to: 'groups#search', as: 'groups_search'
  resources :groups do
    resources :memberships, only: [:index, :create, :destroy, :update]
    post 'memberships/search', to: 'memberships#search', as: 'memberships_search'
    post 'memberships/add_user/:user_id', to: 'memberships#add_user', as: 'memberships_add'
    resources :categories, path: 'c' do
      resources :tasks
      resource :text_page, only: [:create, :new, :show, :update, :edit]
      get 'text_page/to_authenticate', to: 'text_pages#to_authenticate', as: 'text_page_auth'
      resources :contacts
      resource :display
      get 'display/to_authenticate', to: 'displays#to_authenticate', as: 'display_auth'
      resource :calendar, only: [:create, :new, :show, :update, :edit]
      resources :events
      get 'calendar/to_authenticate', to: 'calendars#to_authenticate', as: 'calendar_auth'
      post 'calendar/show_period', to: 'calendars#show_period', as: 'calendar_period'
      get 'events/google_edit/:id', to: 'events#google_edit', as: 'edit_google_event'

      get 'events/google/:id', to: 'events#google_show', as: 'google_event'
      post 'events/google/:id', to: 'events#google_update'
      delete 'events/google/:id', to: 'events#google_destroy'
      post 'events/index_period', to: 'events#index_period', as: 'events_period'
      post 'events/export_event/:id', to: 'events#export_event', as: 'export_event'
      post 'events/export_all_events', to: 'events#export_all_events', as: 'export_all_events'
    end
    post '/categories_save_order', to: 'categories#saveOrder', as: 'categories_save_order'
  end

  post '/join_group/:id', to: 'groups#join', as: 'join_group'

  get '/auth/:provider/callback', to: 'sessions#auth_callback', as: 'auth_callback'
  post 'register_with_google', to: 'sessions#register_with_google', as: 'register_with_google'
  post 'login_with_google', to: 'sessions#login_with_google', as: 'login_with_google'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string
#  password        :string
#  name            :string
#  email           :string
#  birthday        :date
#  description     :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string
#  remember_digest :string
#  admin           :boolean          default(FALSE)
#

class User < ActiveRecord::Base
  def to_param
    username
  end

  # 0 - ordinary community user
  # 1 - community administrator
  # 2 - kouhaidash administrator

	attr_accessor :remember_token

  has_many :memberships, dependent: :destroy
  has_many :groups, through: :memberships
  has_many :task_assignments, through: :memberships
  has_many :tasks, through: :task_assignments
  #to retrieve events
  has_many :categories, through: :groups
  has_many :calendars, through: :categories
  has_many :events, through: :calendars
  has_one :google_account

	before_save { self.email = email.downcase }

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :username,
						presence: true,
						length: { minimum: 4, maximum: 16 },
						uniqueness: { case_sensitive: false },
            format: { with: /\A[a-zA-Z0-9_-]+\Z/, message: "only allows letters, digits, hyphens and underscores"}
	validates :email,
						presence: true,
						format: { with: VALID_EMAIL_REGEX },
						length: { maximum: 64 },
						uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password,
						presence: true,
						length: { minimum: 8 },
						confirmation: true,
            allow_nil: true

	# Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ?
    	BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :get_user, only: [:show, :edit, :update,
    :correct_user, :destroy, :to_authenticate, :to_revoke]
  before_action :logged_in_user, only: [:index, :edit,
    :update]
  before_action :correct_user, only: [:edit, :update, :to_authenticate, :to_revoke]
  before_action :admin_user, only: :destroy
  before_action :set_google_account, only: [:edit, :update]

  def index
    # raise params.inspect
    # @users = User.paginate(page: params[:page])
    @users = User.all
  end

  def show
    @memberships=@user.memberships.includes(:group).order(:approved)
    if @user==current_user
      @overdue=@user.tasks.includes(:category).where(done: false).where("deadline < ?",Date.today).order('deadline ASC').limit(5)
      @tasks=@user.tasks.includes(:category).where(done: false).where("deadline >= ?",Date.today).order("deadline ASC").limit(5)
      @events=@user.events.includes(calendar: {category: :group}).where('"end" >= ?',Time.now).order("start").where('"start" < ?',Time.now + 7.days).order("start ASC").limit(5).collect{|event|
        {start:event.start, google:false, event:event, category: event.calendar.category_id, time_zone: event.calendar.time_zone , group: event.calendar.category.group.id}}
      @user.calendars.each do |cal|
        next unless cal.google_calendar_id && cal.google_calendar_id.length>0
        begin
          token = cal.google_account.fresh_token
          calendar_client = Signet::OAuth2::Client.new(access_token: token)
          calendar_service = Google::Apis::CalendarV3::CalendarService.new
          calendar_service.authorization = calendar_client
          result= calendar_service.list_events(cal.google_calendar_id, single_events: true, max_results: 5,
            order_by: "startTime",time_max: (Time.now + 7.days).to_datetime.rfc3339,
            time_min: Time.now.to_datetime.rfc3339)
          @events.concat(result.items.collect{|event|{start: event.start.date_time,google: true, event:event, category: cal.category_id, time_zone:cal.time_zone, group: cal.category.group.id}})
        rescue
        end
      end
      @events.sort!{
        |x,y| x[:start]<=>y[:start]
      }
      @events=@events.first(5)
    end
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
    if @user.save
      log_in @user
      remember @user
    	flash[:success] = "Welcome to KouhaiDash!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile Updated!"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def delete
  end

  def destroy
    @user.destroy
    flash[:success] = "User Deleted!"
    redirect_to users_url
  end

  def to_authenticate
    store_location_url(edit_user_path(@user))
    redirect_to '/auth/google_oauth2'
  end

  def to_revoke
    if revoke_google_token(@user.google_account.fresh_token)
      flash[:notice] = 'The google account is no longer associated with your account. Permissions for KouhaiDash are also revoked.'
    end
    @user.google_account.destroy
    redirect_to edit_user_path(@user)
  end

 	private

   	def user_params
   		params.require(:user).permit(
   			:username, :email,
   			:password, :password_confirmation,
   			:name, :birthday, :description,
   			:image, :remove_image,
   			:organisation, :position
  		)
  	end

    def get_user
      # raise params.inspect
      @user = User.find_by_username(params[:id])
    end

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please login."
        redirect_to login_url
      end
    end

    # Confirms the correct user.
    def correct_user
      redirect_to(root_url) unless @user == current_user
    end

    def same_user
      correct_user
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

    def set_google_account
      @google_account=@user.google_account
      if @google_account
        @google_account.refresh!
        unless @google_account.refresh_token.length>0
          @revoked = true
          revoke_google_token(@google_account.access_token)
          flash.now[:notice] = 'Permissions from your google account has expired. Please sign in with google again to renew the permissions.'
        end
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
	# Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_user.html.erb
<div class='col s12 m6'>
  <div class="card medium">
    <div class="card-image waves-effect waves-block waves-light">
      <%= image_tag "default#{user.id%4}.jpg", class:'activator' %>
    </div>
    <div class="card-content">
      <span class="activator flow-text"><%=user.username%><i class="material-icons right">more_vert</i></span>
      <p></p>
    </div>
    <div class='card-action'>
      <%= link_to "<i class='material-icons'>info</i>".html_safe, user %>
      <% if current_user.admin? && !current_user?(user) %>
          <%= link_to "delete", user, method: :delete, data: { confirm: "Delete #{user.username}?" } %>
      <%end%>
    </div>
    <div class="card-reveal">
      <span class="card-title grey-text text-darken-4"><%=user.username %><i class="material-icons right">close</i></span>
      <p><%=user.description%></p>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Update " + @user.username) %>
<div class="row">
  <div class='col s12'>
    <h1>User Settings for <%= @user.username %></h1>
  </div>
</div>

<div class="row">
  <div class="col s12 m9">
    <%= form_for(@user) do |f| %>
      <%=render 'shared/error_messages'%>
      <div class="input-field col s12">
      <%= f.label :description, 'About Myself' %>
      <%= f.text_area :description, class: 'materialize-textarea'%>
      </div>
      <div class="input-field col s12">
      <%= f.email_field :email, class: 'validate'%>
      <%= f.label :email%>
      </div>

      <div class="input-field col s12">
        <%= f.password_field :password%>
        <%= f.label :password, "New Password"%>
      </div>

      <div class="input-field col s12">
      <%= f.password_field :password_confirmation%>
      <%= f.label :password_confirmation, "Confirm New Password"%>
      </div>

      <div class="actions col s12">
        <p><button class="btn-large waves-effect waves-light" type="submit" name="action">Update
          <i class="material-icons right">send</i>
        </button></p>
      </div>

    <% end %>
  </div>
</div>

<div class = "row">
  <div class='col s12'>
    <h2>Manage Google Account</h2>
  </div>
  <div class='col s12 m9'>
    <!--Manage Google Account-->
    <%if @user.google_account%>
      <table class ='responsive-table'>
        <tr>
          <td><%=@user.google_account.gmail%></td>
          <td><%=link_to '<i class="material-icons">remove_circle</i>'.html_safe,to_revoke_user_path(@user),
              class: "btn waves-effect waves-light tooltipped red", data: {position:"bottom", delay:"50",tooltip:"Sign out from Google"}%>
          </td>
          <%if @revoked%>
            <td><%=link_to '<i class="material-icons">refresh</i>'.html_safe,to_authenticate_user_path(@user),
                class: "btn waves-effect waves-light tooltipped", data: {position:"bottom", delay:"50",tooltip:"Renew permissions"}%>
            </td>
          <%end%>
          </table>
        </tr>

    <%else%>
    <p>
      <%=link_to 'Sign in with Google',to_authenticate_user_path(@user),
          class: "btn waves-effect waves-light"%>
    </p>
    <%end%>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Community') %>
<div class="row">
	<h1>Your KouhaiDash! Community</h1>
</div>

<div class="row">
  <%= render @users %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Register') %>
<div class="row">
  <h1>Register</h1>
</div>

<div class="row">
  <div class="col s12 m9">
    <%= form_for(@user) do |f| %>
    	<%= render 'shared/error_messages' %>
      <div class="input-field col s12">
      <%= f.text_field :username%>
      <%= f.label :username %>
      </div>

      <div class="input-field col s12">
      <%= f.email_field :email%>
      <%= f.label :email %>
      </div>

      <div class="input-field col s12">
      <%= f.password_field :password %>
      <%= f.label :password %>
      </div>

      <div class="input-field col s12">
      <%= f.password_field :password_confirmation %>
      <%= f.label :password_confirmation, "Confirm Password" %>
      </div>

      <div class="actions col s12">
        <p><button class="btn-large waves-effect waves-light" type="submit" name="action">Register
          <i class="material-icons right">send</i>
        </button></p>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.username) %>
<div class="row">
	<h1><%= @user.username %></h1>
</div>

<div class="row dashboard-grid">
  <div class="col s12 m6 grid-item">
   <div class="card">
     <div class="card-image">
       <%= image_tag "default#{@user.id%4}.jpg" %>
     </div>
     <div class="card-content">
       <span class="card-title"><%= @user.username %></span>
       <p><%= @user.description %></p>
     </div>
   </div>
  </div>
  <!-- groups -->
  <div class="col s12 m6 grid-item">
    <div class="card dash-groups">
      <div class="card-content">
        <span class="card-title">Joined Groups</span>
        <%if @memberships.empty?%>
          <p>No joined groups.</p>
        <%else%>
          <table class='highlight'>
            <thead><th>Group</th><th>Status</th></thead>
            <%@memberships.each do |mem|%>
              <tr>
                <td><%=link_to mem.group.name, mem.group%></td>
                <% if mem.approved%>
                  <td class='tooltipped' data-position="bottom" data-delay="50" data-tooltip="Official Member"><i class='material-icons'>person</i></td>
                <%else%>
                  <td class='tooltipped' data-position="bottom" data-delay="50" data-tooltip="Not approved yet :("><i class='material-icons'>person_outline</i></td>
                <%end%>
              </tr>
            <%end%>
          </table>
        <%end%>
      </div>
    </div>
  </div>

  <% if @user==current_user%>

    <!-- overdue tasks -->
    <div class="col s12 m6 grid-item">
      <div class="card dash-overdue">
        <div class="card-content">
          <span class="card-title">Overdue Tasks</span>
          <%if @overdue.empty?%>
            <p>No overdue tasks.</p>
          <%else%>
            <table class='highlight'>
              <%@overdue.each do |task|%>
                <tr>
                  <td><%=link_to task.name, group_category_task_path(task.category.group_id,task.category_id,task)%></td>
                  <td><%=task.deadline.strftime('%e %b %4Y')%></td>
                </tr>
              <%end%>
            </table>
          <%end%>
        </div>
      </div>
    </div>

    <!-- events -->
    <div class="col s12 m6 grid-item">
      <div class="card dash-events">
        <div class="card-content">
          <span class="card-title">Upcoming Events</span>
          <%if @events.empty?%>
            <p>No upcoming events.</p>
          <%else%>
            <table class='highlight'>
              <%@events.each do |hash|%>
                <tr>
                  <%if hash[:google]%>
                    <td><%=link_to hash[:event].summary, group_category_google_event_path(hash[:group],hash[:category],hash[:event].id)%></td>
                  <%else%>
                    <td><%=link_to hash[:event].summary, group_category_event_path(hash[:group],hash[:category],hash[:event])%></td>
                  <%end%>
                  <td><%=hash[:start].to_time.in_time_zone(hash[:time_zone]).strftime('%e %B %4Y %R')%></td>
                </tr>
              <%end%>
            </table>
          <%end%>
        </div>
      </div>
    </div>

    <!-- tasks -->
    <div class="col s12 m6 grid-item">
      <div class="card dash-tasks">
        <div class="card-content">
          <span class="card-title">Upcoming Tasks</span>
          <%if @tasks.empty?%>
            <p>No upcoming tasks.</p>
          <%else%>
            <table class='highlight'>
              <%@tasks.each do |task|%>
                <tr>
                  <td><%=link_to task.name, group_category_task_path(task.category.group_id,task.category_id,task)%></td>
                  <td><%=task.deadline.strftime('%e %b %4Y')%></td>
                </tr>
              <%end%>
            </table>
          <%end%>
        </div>
      </div>
    </div>
    <%end%>

</div>