config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users do
    member do
      get 'to_authenticate'
      get 'to_revoke'
    end
  end

  get 'register', to: 'users#new', as: 'register'

  root 'pages#home'

  get 'pages/profile'

  get 'calendar', to: 'pages#calendar', as: 'calendar'

  get 'pages/tasks'

  get 'files', to: 'pages#files', as: 'files'

  get 'g/:string_id', to: 'groups#show_by_string_id', as:'group_string'
  post 'groups/search', to: 'groups#search', as: 'groups_search'
  resources :groups do
    resources :memberships, only: [:index, :create, :destroy, :update]
    post 'memberships/search', to: 'memberships#search', as: 'memberships_search'
    post 'memberships/add_user/:user_id', to: 'memberships#add_user', as: 'memberships_add'
    resources :categories, path: 'c' do
      resources :tasks
      resource :text_page, only: [:create, :new, :show, :update, :edit]
      get 'text_page/to_authenticate', to: 'text_pages#to_authenticate', as: 'text_page_auth'
      resources :contacts
      resource :display
      get 'display/to_authenticate', to: 'displays#to_authenticate', as: 'display_auth'
      resource :calendar, only: [:create, :new, :show, :update, :edit]
      resources :events
      get 'calendar/to_authenticate', to: 'calendars#to_authenticate', as: 'calendar_auth'
      post 'calendar/show_period', to: 'calendars#show_period', as: 'calendar_period'
      get 'events/google_edit/:id', to: 'events#google_edit', as: 'edit_google_event'

      get 'events/google/:id', to: 'events#google_show', as: 'google_event'
      post 'events/google/:id', to: 'events#google_update'
      delete 'events/google/:id', to: 'events#google_destroy'
      post 'events/index_period', to: 'events#index_period', as: 'events_period'
      post 'events/export_event/:id', to: 'events#export_event', as: 'export_event'
      post 'events/export_all_events', to: 'events#export_all_events', as: 'export_all_events'
    end
    post '/categories_save_order', to: 'categories#saveOrder', as: 'categories_save_order'
  end

  post '/join_group/:id', to: 'groups#join', as: 'join_group'

  get '/auth/:provider/callback', to: 'sessions#auth_callback', as: 'auth_callback'
  post 'register_with_google', to: 'sessions#register_with_google', as: 'register_with_google'
  post 'login_with_google', to: 'sessions#login_with_google', as: 'login_with_google'

end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id          :integer          not null, primary key
#  calendar_id :integer
#  summary     :string
#  location    :string
#  description :text
#  start       :datetime
#  end         :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Event < ActiveRecord::Base
  belongs_to :calendar

  validates :summary,
    presence: true
  validates :calendar_id,
    presence: true
  validate :start_cannot_be_after_than_end

  private
  def start_cannot_be_after_than_end
    unless start
      errors.add(:start,"can't be blank")
    end
    unless self.end
      errors.add(:end,"can't be blank")
    end
    if start && self.end && start > self.end
      errors.add(:start, "can't be after than End datetime")
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_variables
  before_action :check_view_auth
  before_action :check_edit_auth, except: [:index, :show, :google_show, :index_period]
  before_action :check_created
  before_action :set_event, only: [:edit, :update, :show, :destroy, :export_event]
  before_action :set_google_event, only:[:google_edit, :google_show, :google_update]

  # GET /events
  # GET /events.json
  def index
    @events = @calendar.events
    today = Time.now.in_time_zone(@calendar.time_zone).to_datetime
    @period_start= DateTime.new(today.year,today.month,1, 0,0,0,ActiveSupport::TimeZone[@calendar.time_zone].formatted_offset)
    @period_end= DateTime.new(today.next_month.year,today.next_month.month,1, 0,0,0,ActiveSupport::TimeZone[@calendar.time_zone].formatted_offset)
    get_mixed_events(@period_start,@period_end)
    flash.now[:google_msg]=@google_msg if @google_msg
  end

  def index_period
    respond_to do |format|
      format.js{
        period_params=params.require(:period).permit(:start, :end)
        date_start= Date.parse(period_params[:start])
        date_end = Date.parse(period_params[:end]).tomorrow
        @period_start= DateTime.new(date_start.year,date_start.month,date_start.day, 0,0,0,ActiveSupport::TimeZone[@calendar.time_zone].formatted_offset)
        @period_end= DateTime.new(date_end.year,date_end.month,date_end.day, 0,0,0,ActiveSupport::TimeZone[@calendar.time_zone].formatted_offset)
        get_mixed_events(@period_start,@period_end)
      }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.calendar_id=@category.calendar.id
    @event.start &&= DateTime.new(@event.start.year, @event.start.month, @event.start.day,
      params[:start][:hour].to_i, params[:start][:min].to_i, 0, ActiveSupport::TimeZone[@calendar.time_zone].formatted_offset)
    @event.end &&= DateTime.new(@event.end.year, @event.end.month, @event.end.day,
      params[:end][:hour].to_i, params[:end][:min].to_i, 0, ActiveSupport::TimeZone[@calendar.time_zone].formatted_offset)
    respond_to do |format|
      if @event.save
        begin
          #create with google calendar and destroy if possible
          calendar_client = Signet::OAuth2::Client.new(access_token: current_user.google_account.fresh_token)
          calendar_service = Google::Apis::CalendarV3::CalendarService.new
          calendar_service.authorization = calendar_client
          event = Google::Apis::CalendarV3::Event.new(
            summary: @event.summary,
            location: @event.location,
            description: @event.description,
            start: {
              date_time: @event.start.rfc3339
            },
            end: {
              date_time: @event.end.rfc3339
            }
          )
          @google_event = calendar_service.insert_event(@calendar.google_calendar_id, event)
          @event.destroy if @google_event.id
          @event=nil
        rescue Exception => e
          puts e.message
        end
        format.html {
          if @event
            redirect_to [@group,@category,@event], notice: 'Event was successfully created.'
          else
            redirect_to group_category_google_event_path(@group,@category,@google_event.id), notice: 'Google event was successfully created.'
          end
        }
        format.json { render :show, status: :created, location: [@group,@category,@event] }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    update_params=event_params.to_h
    begin
      day= DateTime.parse(update_params['start'])
      update_params['start']= DateTime.new(day.year, day.month, day.day,
        params[:start][:hour].to_i, params[:start][:min].to_i, 0, ActiveSupport::TimeZone[@calendar.time_zone].formatted_offset)
    rescue
    end
    begin
    day= DateTime.parse(update_params['end'])
    update_params['end']= DateTime.new(day.year, day.month, day.day,
      params[:end][:hour].to_i, params[:end][:min].to_i, 0, ActiveSupport::TimeZone[@calendar.time_zone].formatted_offset)
    rescue
    end
    respond_to do |format|
      if @event.update(update_params)
        format.html { redirect_to [@group,@category,@event], notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: [@group,@category,@event] }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to group_category_calendar_path(@group,@category), notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
      format.js{}
    end
  end

  def export_event
    begin
      #create with google calendar and destroy
      calendar_client = Signet::OAuth2::Client.new(access_token: current_user.google_account.fresh_token)
      calendar_service = Google::Apis::CalendarV3::CalendarService.new
      calendar_service.authorization = calendar_client
      event = Google::Apis::CalendarV3::Event.new(
        summary: @event.summary,
        location: @event.location,
        description: @event.description,
        start: {
          date_time: @event.start.to_datetime.rfc3339
        },
        end: {
          date_time: @event.end.to_datetime.rfc3339
        }
      )
      result = calendar_service.insert_event(@calendar.google_calendar_id, event)
      @event.destroy if result.id
      redirect_to group_category_google_event_path(@group,@category,result.id), notice: 'Event was successfully exported to Google Calendar.'
    rescue Exception => e
      puts e.message
      # try again after resetting google settings
      google_settings
      begin
        #create with google calendar and destroy
        calendar_client = Signet::OAuth2::Client.new(access_token: current_user.google_account.fresh_token)
        calendar_service = Google::Apis::CalendarV3::CalendarService.new
        calendar_service.authorization = calendar_client
        event = Google::Apis::CalendarV3::Event.new(
          summary: @event.summary,
          location: @event.location,
          description: @event.description,
          start: {
            date_time: @event.start.to_datetime.rfc3339
          },
          end: {
            date_time: @event.end.to_datetime.rfc3339
          }
        )
        result = calendar_service.insert_event(@calendar.google_calendar_id, event)
        @event.destroy if result.id
        redirect_to group_category_google_event_path(@group,@category,result.id), notice: 'Event was successfully exported to Google Calendar.'
      rescue Exception => e
        puts e.message
        redirect_to group_category_event_path(@group,@category,@event), notice: 'Unable to export event. Please sign in with Google through Settings if you have not done so or check the Google Calendar settings.'
      end
    end
  end

  def export_all_events
    begin
      #create with google calendar and destroy
      @events= @calendar.events
      calendar_client = Signet::OAuth2::Client.new(access_token: current_user.google_account.fresh_token)
      calendar_service = Google::Apis::CalendarV3::CalendarService.new
      calendar_service.authorization = calendar_client
      @events.each do |event|
        g_event = Google::Apis::CalendarV3::Event.new(
          summary: event.summary,
          location: event.location,
          description: event.description,
          start: {
            date_time: event.start.to_datetime.rfc3339
          },
          end: {
            date_time: event.end.to_datetime.rfc3339
          }
        )
        result = calendar_service.insert_event(@calendar.google_calendar_id, g_event)
        event.destroy if result.id
      end
      @success=true
    rescue Exception => e
      puts e.message
      # try again after resetting google settings
      google_settings
      begin
        #create with google calendar and destroy
        @events= @calendar.events
        calendar_client = Signet::OAuth2::Client.new(access_token: current_user.google_account.fresh_token)
        calendar_service = Google::Apis::CalendarV3::CalendarService.new
        calendar_service.authorization = calendar_client
        @events.each do |event|
          g_event = Google::Apis::CalendarV3::Event.new(
            summary: event.summary,
            location: event.location,
            description: event.description,
            start: {
              date_time: event.start.to_datetime.rfc3339
            },
            end: {
              date_time: event.end.to_datetime.rfc3339
            }
          )
          result = calendar_service.insert_event(@calendar.google_calendar_id, g_event)
          event.destroy if result.id
        end
        @success=true
      rescue Exception => e
        puts e.message
        @success=false
      end
    end
    respond_to do |format|
      format.html {
        flash[:notice]=( @success ?
        'Events were successfully exported to Google Calendar.':'Unable to export all events. Please sign in with Google through Settings if you have not done so or check the Google Calendar settings.')
        redirect_to group_category_events_path(@group,@category)
      }
    end
  end

  def google_destroy
    begin
      calendar_client = Signet::OAuth2::Client.new(access_token: current_user.google_account.fresh_token)
      calendar_service = Google::Apis::CalendarV3::CalendarService.new
      calendar_service.authorization = calendar_client

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for([@group, @category, @event]) do |f| %>
  <% if @event.errors.any? %>
    <div class="col s12">
      <div class="alert">
        <p>The form contains <%= pluralize(@event.errors.count, "error") %>.</p>
      </div>
      <ul class='alert'>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field col s12">
    <%= f.text_field :summary %>
    <%= f.label :summary %>
  </div>
  <div class="input-field col s12">
    <%= f.text_field :location %>
    <%= f.label :location %>
  </div>
  <div class="input-field col s12">
    <%= f.text_area :description, class: 'materialize-textarea' %>
    <%= f.label :description %>
  </div>
  <div>
    <div class="input-field col s12 m4">
      <%= f.text_field :start, class:'datepicker', type: 'date', value: "#{(@event.start && @event.start.to_time.in_time_zone(@calendar.time_zone).to_date )|| Time.now.in_time_zone(@calendar.time_zone).to_date}"%>
      <%= f.label :start, "Start Date",class: 'active'%>
    </div>
    <div class="input-field col s6 m4">
      <%=select_hour(@event.start && @event.start.to_time.in_time_zone(@calendar.time_zone),{ field_name: 'hour', prefix:'start'})%>
      <%=label :start, :hour, "hour"%>
    </div>
    <div class="input-field col s6 m4">
      <%=select_minute(@event.start && @event.start.to_time.in_time_zone(@calendar.time_zone),{ field_name: 'min', prefix:'start'})%>
      <%=label :start, :min, "minute"%>
    </div>
  </div>
  <div>
    <div class="input-field col s12 m4">
      <%= f.text_field :end, class:'datepicker', type: 'date',value: "#{(@event.end && @event.end.to_time.in_time_zone(@calendar.time_zone).to_date )|| Time.now.in_time_zone(@calendar.time_zone).to_date}"%>
      <%= f.label :end, "End Date",class: 'active'%>
    </div>
    <div class="input-field col s6 m4">
      <%=select_hour(@event.end && @event.end.to_time.in_time_zone(@calendar.time_zone),{ field_name: 'hour', prefix:'end'})%>
      <%=label :end, :hour, "hour"%>
    </div>
    <div class="input-field col s6 m4">
      <%=select_minute(@event.end && @event.end.to_time.in_time_zone(@calendar.time_zone),{ field_name: 'min', prefix:'end'})%>
      <%=label :end, :min, "minute"%>
    </div>
  </div>
  <div class="actions col s12">
    <p><button class="btn-large waves-effect waves-light" type="submit" name="action">Submit
      <i class="material-icons right">send</i>
    </button></p>
  </div>
<% end %>

app/views/events/_table.html.erb
<thead>
  <tr>
    <th>Summary</th>
    <th>Start</th>
    <th>End</th>
    <% if @authorised_member%>
      <th colspan="2"></th>
    <%end%>
  </tr>
</thead>

<tbody>
  <% @mixed_events.each do |hash| %>
    <% if hash[:google]%>
      <%google_event=hash[:event]%>
      <tr id='g_<%=google_event.id%>_row'>
        <td><%= link_to google_event.summary||'(No Title)', group_category_google_event_path(@group,@category,google_event.id) %></td>
        <td><%= google_event.start.date_time.to_time.in_time_zone(@calendar.time_zone).strftime('%e %B %4Y %R') %></td>
        <td><%= google_event.end.date_time.to_time.in_time_zone(@calendar.time_zone).strftime('%e %B %4Y %R') %></td>
        <% if @authorised_member%>
          <td><%= link_to '<i class="material-icons">mode_edit</i>'.html_safe, group_category_edit_google_event_path(@group,@category,google_event.id) %></td>
          <td><%= link_to '<i class="material-icons">delete</i>'.html_safe, group_category_google_event_path(@group,@category,google_event.id),
            remote: true, method: :delete, data: { confirm: 'Are you sure?' }, class: 'red-text'  %></td>
        <%end%>
      </tr>
    <% else %>
      <%event=hash[:event]%>
      <tr id='l_<%=event.id%>_row'>
        <td><%= link_to event.summary, [@group,@category,event] %></td>
        <td><%= event.start.to_time.in_time_zone(@calendar.time_zone).strftime('%e %B %4Y %R') %></td>
        <td><%= event.end.to_time.in_time_zone(@calendar.time_zone).strftime('%e %B %4Y %R') %></td>
        <% if @authorised_member%>
          <td><%= link_to '<i class="material-icons">mode_edit</i>'.html_safe, edit_group_category_event_path(@group,@category,event) %></td>
          <td><%= link_to '<i class="material-icons">delete</i>'.html_safe, [@group,@category,event],
          remote: true, method: :delete, data: { confirm: 'Are you sure?' }, class: 'red-text' %></td>
        <%end%>
      </tr>
    <%end%>
  <% end %>
</tbody>

app/views/events/destroy.js.erb
$('#l_<%=@event.id%>_row').hide('fast');

app/views/events/edit.html.erb
<% provide(:title, "Edit #{@event.summary}") %>
<div class="row">
  <div class="col s12">
    <h1>Edit <%=@event.summary%></h1>
  </div>
</div>
<div class="row">
  <div class="col s12 m9">
    <%= render 'form' %>
  </div>
</div>

app/views/events/google_destroy.js.erb
<%if @success%>
  $('#g_<%=@id%>_row').hide('fast');
<%else%>
  Materialize.toast('Attempt to delete Google Event was unsuccessful.');
<%end%>

app/views/events/google_edit.html.erb
<% provide(:title, "Edit #{@google_event.summary||'(No Title)'}") %>
<div class="row">
  <div class="col s12">
    <h1>Edit <%=@google_event.summary||'(No Title)'%></h1>
  </div>
</div>
<div class="row">
  <div class="col s12 m9">
    <%= form_tag group_category_google_event_path(@group,@category,@google_event.id) do %>
      <div class="input-field col s12">
        <%= text_field :google_event, :summary %>
        <%= label :google_event, :summary %>
      </div>
      <div class="input-field col s12">
        <%= text_field :google_event, :location %>
        <%= label :google_event, :location %>
      </div>
      <div class="input-field col s12">
        <%= text_area :google_event, :description, class: 'materialize-textarea' %>
        <%= label :google_event, :description %>
      </div>
      <div>
        <div class="input-field col s12 m4">
          <%= text_field :google_event, :start, class:'datepicker', type: 'date', value: "#{@google_event.start.date_time.to_date}"%>
          <%= label :google_event, :start, "Start Date",class: 'active'%>
        </div>
        <div class="input-field col s6 m4">
          <%=select_hour(@google_event.start.date_time,{ field_name: 'hour', prefix:'start'})%>
          <%=label :start, :hour, "hour"%>
        </div>
        <div class="input-field col s6 m4">
          <%=select_minute(@google_event.start.date_time,{ field_name: 'min', prefix:'start'})%>
          <%=label :start, :min, "minute"%>
        </div>
      </div>
      <div>
        <div class="input-field col s12 m4">
          <%= text_field :google_event, :end, class:'datepicker', type: 'date',value: "#{@google_event.end.date_time.to_date}"%>
          <%= label :google_event, :end, "End Date",class: 'active'%>
        </div>
        <div class="input-field col s6 m4">
          <%=select_hour(@google_event.end.date_time,{ field_name: 'hour', prefix:'end'})%>
          <%=label :end, :hour, "hour"%>
        </div>
        <div class="input-field col s6 m4">
          <%=select_minute(@google_event.end.date_time,{ field_name: 'min', prefix:'end'})%>
          <%=label :end, :min, "minute"%>
        </div>
      </div>
      <div class="actions col s12">
        <p><button class="btn-large waves-effect waves-light" type="submit" name="action">Submit
          <i class="material-icons right">send</i>
        </button></p>
      </div>
    <% end %>
  </div>
</div>

app/views/events/google_show.html.erb
<% provide(:title, "#{@google_event.summary||'(No Title)'}") %>
<div class="row">
  <div class="col s12">
    <h1><%=@google_event.summary||'(No Title)'%></h1>
  </div>
</div>
<div class="row">
  <div class="col s12">
    <table class="table">
      <tbody>
        <tr>
          <th>Start</th>
          <td><%= @google_event.start.date_time.to_time.in_time_zone(@calendar.time_zone).strftime('%e %B %4Y %R') %></td>
        </tr>
        <tr>
          <th>End</th>
          <td><%= @google_event.end.date_time.to_time.in_time_zone(@calendar.time_zone).strftime('%e %B %4Y %R') %></td>
        </tr>
        <tr>
          <th>Location</th>
          <td><%= @google_event.location %></td>
        </tr>
        <tr>
          <th>Description</th>
          <td><%= @google_event.description %></td>
        </tr>
        <tr>
          <th>Google link</th>
          <td><div ><%=link_to 'Google Event link', @google_event.html_link%></div></td>
        </tr>
      </tbody>
     </table>
  </div>
</div>

<div class="row">
  <div class=" col s12">
    <%if @authorised_member %>
      <%= link_to "<i class='material-icons'>mode_edit</i>".html_safe, group_category_edit_google_event_path(@group,@category,@google_event.id),
        class: "btn waves-effect waves-light tooltipped", data: {position:"bottom", delay:"50",tooltip:"Update"}%>
        <%= link_to '<i class="material-icons">delete</i>'.html_safe, group_category_google_event_path(@group,@category,@google_event.id), method: :delete,
          data: { confirm: 'Are you sure?',position:"bottom", delay:"50",tooltip:"Delete"}, class: "btn waves-effect waves-light tooltipped red"%>
    <%end%>
    <%= link_to '<i class="material-icons">date_range</i>'.html_safe, group_category_calendar_path(@group,@category),
      class: "btn waves-effect waves-light tooltipped",data: {position:"bottom", delay:"50",tooltip:"Return to calendar"} %>
    <%= link_to '<i class="material-icons">list</i>'.html_safe, group_category_events_path(@group,@category),
      class: "btn waves-effect waves-light tooltipped",data: {position:"bottom", delay:"50",tooltip:"Return to list"} %>
  </div>
</div>

app/views/events/index.html.erb
<% provide(:title, "#{@calendar.name && @calendar.name.length>0? @calendar.name : @category.name}") %>
<div class="row">
  <h1><%=@calendar.name && @calendar.name.length>0? @calendar.name : @category.name%></h1>
</div>

<div class="row">
  <div class = "col s12">
    <% if @authorised_member%>
      <%= link_to '<i class="material-icons">settings</i>'.html_safe,edit_group_category_calendar_path(@group,@category),
        class: "btn waves-effect waves-light tooltipped", data:{position:"bottom", delay:"50",tooltip:"Settings"}  %>
      <a class= "red btn waves-effect waves-light" href='<%=new_group_category_event_path(@group,@category)%>'><i class="material-icons left">add</i> New Event</a>
      <% unless @calendar.events.empty? ||@calendar.google_calendar_id.nil? || @calendar.google_calendar_id.length==0%>
        <%= link_to '<i class="material-icons">import_export</i>'.html_safe,group_category_export_all_events_path(@group,@category), method: :post,
          class: "btn waves-effect waves-light tooltipped",
          data:{position:"bottom", delay:"50",tooltip:"Export all local events to Google Calendar"}  %>
      <% end %>
    <% end%>
    <%= link_to '<i class="material-icons">date_range</i>'.html_safe,group_category_calendar_path(@group,@category),
      class: "btn waves-effect waves-light tooltipped", data:{position:"bottom", delay:"50",tooltip:"Calendar View"}  %>
  </div>
</div>

<div class='row'>
  <div>
    <%=form_for(:period, url: group_category_events_period_path(@group, @category),remote: true,  html: {id: "events_period_form" }) do |f|%>
      <div class='input-field col s6 m4'>
        <%= f.text_field :start, class:'datepicker events-period', type: 'date', value: @period_start.to_date%>
        <%= f.label :start, "From",class: 'active'%>
      </div>
      <div class='input-field col s6 m4'>
        <%= f.text_field :end, class:'datepicker events-period', type: 'date', value: @period_end.to_date.yesterday%>
        <%= f.label :end, "Until", class: 'active'%>
      </div>
    <%end%>
  </div>
  <div class='col s12'>
    <table id='events_table'>
      <%=render 'table'%>
    </table>
  </div>
</div>

app/views/events/index_period.js.erb
document.getElementById("events_table").innerHTML = "<%= escape_javascript(render 'table') %>";
<% if @google_msg %>
  Materialize.toast('<%=@google_msg%>');
<% end%>

app/views/events/new.html.erb
<% provide(:title, "New Event") %>
<div class="row">
  <div class="col s12">
    <h1>New Event</h1>
  </div>
</div>
<div class="row">
  <div class="col m9">
    <%= render 'form' %>
  </div>
</div>

app/views/events/show.html.erb
<% provide(:title, "#{@event.summary}") %>
<div class="row">
  <div class="col s12">
    <h1><%=@event.summary%></h1>
  </div>
</div>
<div class="row">
  <div class="col s12">
    <table class="table">
      <tbody>
        <tr>
          <th>Start</th>
          <td><%= @event.start.to_time.in_time_zone(@calendar.time_zone).strftime('%e %B %4Y %R') %></td>
        </tr>
        <tr>
          <th>End</th>
          <td><%= @event.end.to_time.in_time_zone(@calendar.time_zone).strftime('%e %B %4Y %R') %></td>
        </tr>
        <tr>
          <th>Location</th>
          <td><%= @event.location %></td>
        </tr>
        <tr>
          <th>Description</th>
          <td><%= @event.description %></td>
        </tr>

      </tbody>
     </table>
  </div>
</div>

<div class="row">
  <div class=" col s12">
    <%if @authorised_member %>
      <%= link_to "<i class='material-icons'>mode_edit</i>".html_safe, edit_group_category_event_path(@group,@category,@event),
        class: "btn waves-effect waves-light tooltipped", data: {position:"bottom", delay:"50",tooltip:"Update"}%>
      <%= link_to '<i class="material-icons">delete</i>'.html_safe, [@group,@category,@event], method: :delete,
        data: { confirm: 'Are you sure?',position:"bottom", delay:"50",tooltip:"Delete"}, class: "btn waves-effect waves-light tooltipped red"%>
      <% unless (@calendar.google_calendar_id.nil? || @calendar.google_calendar_id.length==0)%>
        <%= link_to '<i class="material-icons">import_export</i>'.html_safe, group_category_export_event_path(@group,@category,@event), method: :post,
          data: { position:"bottom", delay:"50",tooltip:"Export to Google Calendar"}, class: "btn waves-effect waves-light tooltipped"%>
      <%end%>
    <%end%>
    <%= link_to '<i class="material-icons">date_range</i>'.html_safe, group_category_calendar_path(@group,@category),
      class: "btn waves-effect waves-light tooltipped",data: {position:"bottom", delay:"50",tooltip:"Return to calendar"} %>
    <%= link_to '<i class="material-icons">list</i>'.html_safe, group_category_events_path(@group,@category),
      class: "btn waves-effect waves-light tooltipped",data: {position:"bottom", delay:"50",tooltip:"Return to list"} %>
  </div>
</div>