config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users do
    member do
      get 'to_authenticate'
      get 'to_revoke'
    end
  end

  get 'register', to: 'users#new', as: 'register'

  root 'pages#home'

  get 'pages/profile'

  get 'calendar', to: 'pages#calendar', as: 'calendar'

  get 'pages/tasks'

  get 'files', to: 'pages#files', as: 'files'

  get 'g/:string_id', to: 'groups#show_by_string_id', as:'group_string'
  post 'groups/search', to: 'groups#search', as: 'groups_search'
  resources :groups do
    resources :memberships, only: [:index, :create, :destroy, :update]
    post 'memberships/search', to: 'memberships#search', as: 'memberships_search'
    post 'memberships/add_user/:user_id', to: 'memberships#add_user', as: 'memberships_add'
    resources :categories, path: 'c' do
      resources :tasks
      resource :text_page, only: [:create, :new, :show, :update, :edit]
      get 'text_page/to_authenticate', to: 'text_pages#to_authenticate', as: 'text_page_auth'
      resources :contacts
      resource :display
      get 'display/to_authenticate', to: 'displays#to_authenticate', as: 'display_auth'
      resource :calendar, only: [:create, :new, :show, :update, :edit]
      resources :events
      get 'calendar/to_authenticate', to: 'calendars#to_authenticate', as: 'calendar_auth'
      post 'calendar/show_period', to: 'calendars#show_period', as: 'calendar_period'
      get 'events/google_edit/:id', to: 'events#google_edit', as: 'edit_google_event'

      get 'events/google/:id', to: 'events#google_show', as: 'google_event'
      post 'events/google/:id', to: 'events#google_update'
      delete 'events/google/:id', to: 'events#google_destroy'
      post 'events/index_period', to: 'events#index_period', as: 'events_period'
      post 'events/export_event/:id', to: 'events#export_event', as: 'export_event'
      post 'events/export_all_events', to: 'events#export_all_events', as: 'export_all_events'
    end
    post '/categories_save_order', to: 'categories#saveOrder', as: 'categories_save_order'
  end

  post '/join_group/:id', to: 'groups#join', as: 'join_group'

  get '/auth/:provider/callback', to: 'sessions#auth_callback', as: 'auth_callback'
  post 'register_with_google', to: 'sessions#register_with_google', as: 'register_with_google'
  post 'login_with_google', to: 'sessions#login_with_google', as: 'login_with_google'

end

app/models/calendar.rb
# == Schema Information
#
# Table name: calendars
#
#  id                 :integer          not null, primary key
#  name               :string
#  category_id        :integer
#  google_calendar_id :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  google_account_id  :integer
#  time_zone          :string
#

class Calendar < ActiveRecord::Base
  has_many :events, dependent: :destroy
  belongs_to :category
  belongs_to :google_account

  validates :category_id,
    presence: true
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :set_variables
  before_action :check_view_auth
  before_action :check_edit_auth, only: [:edit, :update, :destroy, :new, :create]
  before_action :check_created, only:[:new, :create]
  before_action :google_access_for_edit, only: [:edit, :update, :new, :create]

  # GET /calendars/1
  # GET /calendars/1.json
  def show
    unless @calendar
      redirect_to new_group_category_calendar_path(@group,@category)
      return
    end
    get_events(Time.now.in_time_zone(@calendar.time_zone).to_datetime)
    flash.now[:google_msg]=@google_msg if @google_msg
  end

  # POST /calendar/show_period
  def show_period
    respond_to do |format|
      format.js{
        period_params=params.require(:period).permit(:month, :year)
        get_events(Date.new(period_params[:year].to_i, period_params[:month].to_i,1))
      }
    end
  end

  # GET /calendars/new
  def new
    @calendar = Calendar.new
  end

  # GET /calendars/1/edit
  def edit
  end

  # POST /calendars
  # POST /calendars.json
  def create
    @calendar = Calendar.new(calendar_params)
    @calendar.category = @category
    check_google_calendar
    respond_to do |format|
      if @calendar.save
        google_settings
        format.html {
          if @new_cal
            if @created
              flash[:google_notice]='New Google Calendar was successfully created.'
            else
              flash[:google_notice]='There was an issue with creating the new Google Calendar.'
            end
          end
          flash[:google_settings]='Attempt to change ACL for Google Calendar failed.' if @settings_failed
          flash[:notice]='Calendar was successfully created.'
          redirect_to group_category_calendar_path(@group,@category)
        }
        format.json { render :show, status: :created, location: group_category_calendar_path(@group,@category) }
      else
        format.html {
          if @new_cal
            if @created
              flash.now[:google_notice]='New Google Calendar was successfully created.'
            else
              flash.now[:google_notice]='There was an issue with creating the new Google Calendar.'
            end
          end
          render :new
        }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calendars/1
  # PATCH/PUT /calendars/1.json
  def update
    check_google_calendar
    respond_to do |format|
      if @calendar.update(calendar_params)
        google_settings
        format.html {
          if @new_cal
            if @created
              flash[:google_notice]='New Google Calendar was successfully created.'
            else
              flash[:google_notice]='There was an issue with creating the new Google Calendar.'
            end
          end
          flash[:google_settings]='Attempt to change ACL for Google Calendar failed.' if @settings_failed
          flash[:notice]='Calendar was successfully updated.'
          redirect_to group_category_calendar_path(@group,@category)
        }
        format.json { render :show, status: :ok, location: group_category_calendar_path(@group,@category) }
      else
        format.html {
          if @new_cal
            if @created
              flash.now[:google_notice]='New Google Calendar was successfully created.'
            else
              flash.now[:google_notice]='There was an issue with creating the new Google Calendar.'
            end
          end
          render :edit }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calendars/1
  # DELETE /calendars/1.json
  def destroy
    @calendar.destroy
    respond_to do |format|
      format.html { redirect_to @group,@category, notice: 'Calendar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def to_authenticate
    store_location_url(
      if @calendar
        edit_group_category_calendar_path(@group,@category)
      else
        new_group_category_calendar_path(@group,@category)
      end)
    redirect_to '/auth/google_oauth2'
  end

  private
    def get_events(date)

      day_start=DateTime.new(date.year,date.month,1,0,0, 0, ActiveSupport::TimeZone[@calendar.time_zone].formatted_offset)
      day_end=DateTime.new(date.year,date.month,1,23,59,59, ActiveSupport::TimeZone[@calendar.time_zone].formatted_offset)
      month_start = DateTime.new(date.year,date.month,1,0,0, 0, ActiveSupport::TimeZone[@calendar.time_zone].formatted_offset)
      month_end = DateTime.new(date.next_month.year,date.next_month.month,1,0,0, 0, ActiveSupport::TimeZone[@calendar.time_zone].formatted_offset)
      @start=day_start.cwday%7
      @days_in_month=Time.days_in_month(date.month,date.year)
      @day_events=Array.new(@days_in_month,nil)
      @google_events=[]
      @events= @calendar.events.where.not('"start" >= ?', month_end).where.not('"end" < ?', month_start).order(:start).to_a
      @events.shift while !@events.empty? && @events.first.start<month_start
      if @calendar.google_calendar_id && @calendar.google_calendar_id.length>0
        #load google calendar events
        begin
          token = (current_user && current_user.google_account && current_user.google_account.fresh_token) || @calendar.google_account.fresh_token
          calendar_client = Signet::OAuth2::Client.new(access_token: token)
          calendar_service = Google::Apis::CalendarV3::CalendarService.new
          calendar_service.authorization = calendar_client
          result= calendar_service.list_events(@calendar.google_calendar_id, single_events: true,
            order_by: "startTime",time_max: month_end.rfc3339,
            time_min: month_start.rfc3339)
          @google_events=result.items
        rescue
          #tries reset google calendar settings
          google_settings
          begin
            token = (current_user && current_user.google_account && current_user.google_account.fresh_token) || @calendar.google_account.fresh_token
            calendar_client = Signet::OAuth2::Client.new(access_token: token)
            calendar_service = Google::Apis::CalendarV3::CalendarService.new
            calendar_service.authorization = calendar_client
            result= calendar_service.list_events(@calendar.google_calendar_id, single_events: true,
              order_by: "startTime",time_max: month_end.rfc3339,
              time_min: month_start.rfc3339)
            @google_events=result.items
          rescue
            @google_msg='There was an issue loading events from the Google Calendar.'
          end
        end
      end

      gIdx=0
      eIdx=0
      for i in (0..@days_in_month-1)
        @day_events[i]=[]
        if gIdx<@google_events.length
          gIdx+=1 while gIdx< @google_events.length && @google_events[gIdx].end.date_time<day_start
          idx=gIdx
          while idx<@google_events.length && @google_events[idx].start.date_time<=day_end
            @day_events[i].push({event:@google_events[idx],id:idx, google:true}) if @google_events[idx].end.date_time>day_start || @google_events[idx].start.date_time==day_start
            idx+=1
          end
        end
        if eIdx<@events.length
          eIdx+=1 while eIdx< @events.length && @events[eIdx].end<day_start
          idx=eIdx
          while idx<@events.length && @events[idx].start<=day_end
            @day_events[i].push({event:@events[idx],id:idx, google:false}) if @events[idx].end>day_start || @events[idx].start==day_start
            idx+=1
          end
        end
        day_start=day_start.next_day
        day_end=day_end.next_day
      end
    end

    def check_google_calendar
      if params.fetch(:gradio,false)
        opt=params.fetch(:gradio)
        case opt
        when "current"
          @calendar.google_account_id=current_user.google_account.id
        when "no"
          @calendar.google_calendar_id = nil
        when "select"
          if params.fetch(:google,false)
            @calendar.google_calendar_id=params.fetch(:google).fetch(:calendar_id,@calendar.google_calendar_id)
            @calendar.google_account_id=current_user.google_account.id
          end
        when "new"
          @new_cal=true
          if params.fetch(:google,false)
            begin
              calendar_client = Signet::OAuth2::Client.new(access_token: @google_token)
              calendar_service = Google::Apis::CalendarV3::CalendarService.new
              calendar_service.authorization = calendar_client
              cal_name = params.fetch(:google).fetch(:name,@calendar.name)
              cal_name = @category.name unless cal_name && cal_name.length>0
              calendar =  Google::Apis::CalendarV3::Calendar.new(summary: cal_name)
              result = calendar_service.insert_calendar(calendar)
              @calendar.google_calendar_id=result.id
              @created=result.id
              result = calendar_service.list_calendar_lists(min_access_role: "owner")
              @calendar_array=result.items.collect{|cal| [cal.summary, cal.id]}
              @calendar.google_account_id=current_user.google_account.id
            rescue
            end
          end
        end
      end
    end

    def google_settings
      if @calendar.google_calendar_id && @calendar.google_calendar_id.length>0
        calendar_service = Google::Apis::CalendarV3::CalendarService.new
        group= Group.includes(memberships:{user: :google_account}).find(@group.id)
        accounts=group.memberships.collect{|member|
          {account: member.user.google_account, is_owner: false} if member.approved && member.user.google_account
        }
        #try to find an owner account
        begin
          #find using stored google_account
          calendar_client = Signet::OAuth2::Client.new(access_token: @calendar.google_account.fresh_token)
          calendar_service.authorization = calendar_client

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/views/calendars/_form.html.erb
<%= form_for([@group,@category,@calendar], url: group_category_calendar_path(@group,@category)) do |f| %>
  <% if @calendar.errors.any? %>
    <div class="col s12">
      <div class="alert">
        <p>The form contains <%= pluralize(@calendar.errors.count, "error") %>.</p>
      </div>
      <ul class='alert'>
      <% @calendar.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field col s12">
    <%= f.text_field :name , placeholder: @category.name%>
    <%= f.label :name %>
  </div>

  <div class="input-field col s12">
    <%= f.select :time_zone, options_for_select(ActiveSupport::TimeZone.all.collect{|zone| [zone.to_s,zone.name]}, (@calendar && @calendar.time_zone)||'UTC')%>
    <%= f.label :time_zone %>
  </div>

  <%if @google_token%>
    <div class= 'col s12'>
      <h5>Connect to Google Calendar</h5>
    </div>
    <%if @calendar.google_calendar_id%>
      <div class="input-field col s12">
        <p>
          <input name="gradio" type="radio" id="gradio_current" class='calendar_radio' checked value='current'/>
          <label for="gradio_current">Current Google Calendar: <%=@google_calendar_name||@calendar.google_calendar_id%></label>
        </p>
      </div>
    <%end%>
    <div class="input-field col s12">
      <p>
        <input name="gradio" type="radio" id="gradio_no" class='calendar_radio' value='no'/>
        <label for="gradio_no">Not to connect with Google Calendar</label>
      </p>
    </div>
    <div class="input-field col s12">
      <p>
        <input name="gradio" type="radio" id="gradio_select" class='calendar_radio' value='select'/>
        <label for="gradio_select">Choose Google Calendar</label>
        <br><br>
      </p>
    </div>
    <div class="input-field col s11 offset-s1">
      <%= select :google, :calendar_id, options_for_select(@calendar_array, @calendar.google_calendar_id)%>
      <%= label :google, :calendar_id, 'Google Calendar'%>
    </div>
    <div class="input-field col s12">
      <p>
        <input name="gradio" type="radio" id="gradio_new" class='calendar_radio' value='new'/>
        <label for="gradio_new">Create new Google Calendar</label>
        <br><br>
      </p>
    </div>
    <div class="input-field col s11 offset-s1">
      <%= text_field :google, :name %>
      <%= label :google, :name , "New Google Calendar Name"%>
    </div>
  <%else%>
    <div id='google-authenicate' class='col s12'>
      <br>
      <%=link_to 'Sign in and load from Google Docs',group_category_calendar_auth_path(@group,@category),class:'btn waves-effect waves-light'%>
    </div>
  <%end%>
  <div class="actions col s12">
    <p><br><button class="btn-large waves-effect waves-light" type="submit" name="action">Submit
      <i class="material-icons right">send</i>
    </button></p>
  </div>
<% end %>

app/views/calendars/_modals.html.erb
<%@google_events.each_index do |i|%>
  <div id="google_modal<%=i%>" class="modal">
    <div class="modal-content">
      <h4><%=@google_events[i].summary%></h4>
      <table>
        <tr>
          <th>Start</th>
          <td><%=@google_events[i].start.date_time.strftime("%D %R")%></td>
        </tr>
        <tr>
          <th>End</th>
          <td><%=@google_events[i].end.date_time.strftime("%D %R")%></td>
        </tr>
        <tr>
          <th>Location</th>
          <td><%=@google_events[i].location%></td>
        </tr>
        <tr>
          <th>Description</th>
          <td><%=@google_events[i].description%></td>
        </tr>
      </table>
    </div>
    <div class="modal-footer">
      <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat"><i class='material-icons'>done</i></a>
      <a href="<%=group_category_google_event_path(@group,@category,@google_events[i].id)%>" class=" modal-action waves-effect
        waves-green btn-flat teal-text"><i class='material-icons'>info</i></a>
      <% if @authorised_member%>
        <a href="<%=group_category_edit_google_event_path(@group,@category,@google_events[i].id)%>" class=" modal-action waves-effect waves-green btn-flat teal-text"><i class='material-icons'>mode_edit</i></a>
      <% end%>
    </div>
  </div>
<%end%>
<%@events.each_index do |i|%>
  <div id="modal<%=i%>" class="modal">
    <div class="modal-content">
      <h4><%=@events[i].summary%></h4>
      <table>
        <tr>
          <th>Start</th>
          <td><%=@events[i].start.to_time.in_time_zone(@calendar.time_zone).strftime("%D %R")%></td>
        </tr>
        <tr>
          <th>End</th>
          <td><%=@events[i].end.to_time.in_time_zone(@calendar.time_zone).strftime("%D %R")%></td>
        </tr>
        <tr>
          <th>Location</th>
          <td><%=@events[i].location%></td>
        </tr>
        <tr>
          <th>Description</th>
          <td><%=@events[i].description%></td>
        </tr>
      </table>
    </div>
    <div class="modal-footer">
      <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat"><i class='material-icons'>done</i></a>
      <a href="<%=group_category_event_path(@group,@category,@events[i])%>" class=" modal-action waves-effect waves-green 
        btn-flat teal-text"><i class='material-icons'>info</i></a>
      <% if @authorised_member%>
        <a href="<%=edit_group_category_event_path(@group,@category,@events[i])%>" class=" modal-action waves-effect waves-green btn-flat teal-text"><i class='material-icons'>mode_edit</i></a>
      <% end%>
    </div>
  </div>
<%end%>

app/views/calendars/_table.html.erb
<tr>
  <%wdays=['Sun','Mon','Tue','Wed','Thu','Fri','Sat']%>
  <%wdays.each do |day|%>
    <th><%=day%></th>
  <%end%>
</tr>
<%day=0%>
<%while day<@days_in_month%>
  <tr>
    <%if @start>0%>
      <td colspan="<%=@start%>"></td>
    <%end%>
    <%left=7-@start%>
    <%@start=0%>
    <%while left>0 && day<@days_in_month%>
      <%day+=1%>
      <%left-=1%>
      <td class='calendar-td'>
        <p class='day-<%=left%>'><%=day%><br>
        <%@day_events[day-1].each do |hash|%>
          <a class='modal-trigger calendar-link' style="display:block;" href='#<%='google_' if hash[:google]%>modal<%=hash[:id]%>'><%=hash[:event].summary || '(No Title)'%></a>
        <%end%>
        </p>
      </td>
    <%end%>
    <%if left>0%>
      <td colspan="<%=left%>"></td>
    <%end%>
  </tr>
<%end%>

app/views/calendars/edit.html.erb
<% provide(:title, "Edit #{@calendar.name && @calendar.name.length>0? @calendar.name : @category.name}") %>
<div class="row">
  <div class="col s12">
    <h1>Edit <%=@calendar.name && @calendar.name.length>0? @calendar.name : @category.name%></h1>
  </div>
</div>
<div class="row">
  <div class="col s12 m9">
    <%= render 'form' %>
  </div>
</div>

app/views/calendars/new.html.erb
<% provide(:title, "New Calendar") %>
<div class="row">
  <div class="col s12">
    <h1>New Calendar</h1>
  </div>
</div>
<div class="row">
  <div class="col m9">
    <%= render 'form' %>
  </div>
</div>

app/views/calendars/show.html.erb
<% provide(:title, "#{@calendar.name && @calendar.name.length>0? @calendar.name : @category.name}") %>
<div class="row">
  <h1><%=@calendar.name && @calendar.name.length>0? @calendar.name : @category.name%></h1>
</div>


<div class="row">
  <div class = "col s12">
    <% if @authorised_member%>
      <%= link_to '<i class="material-icons">settings</i>'.html_safe,edit_group_category_calendar_path(@group,@category),
        class: "btn waves-effect waves-light tooltipped", data:{position:"bottom", delay:"50",tooltip:"Settings"}  %>
      <a class= "red btn waves-effect waves-light" href='<%=new_group_category_event_path(@group,@category)%>'><i class="material-icons left">add</i> New Event</a>
    <% end%>
    <%= link_to '<i class="material-icons">list</i>'.html_safe,group_category_events_path(@group,@category),
      class: "btn waves-effect waves-light tooltipped", data:{position:"bottom", delay:"50",tooltip:"List View"}  %>

  </div>
</div>
<div class='row'>
  <div class='col s12'>
    <%=form_for(:period, url: group_category_calendar_period_path(@group, @category),remote: true,  html: {id: "calendar_period_form" }) do |f|%>
      <div class='input-field col s6 m4'>
        <%=select_month(Time.now.in_time_zone(@calendar.time_zone).to_date,{ field_name: 'month', prefix:'period'}, {class: 'calendar-period'}) %>
        <%=f.label :month, 'Month'%>
      </div>
      <div class='input-field col s6 m4'>
        <%=select_year(Time.now.in_time_zone(@calendar.time_zone).to_date, {field_name: 'year', prefix:'period'}, {class: 'calendar-period'})%>
        <%=f.label :year, 'Year'%>
      </div>
    <%end%>
  </div>
  <div class='col s12'>
    <table class='bordered calendar-table' id='calendar_table'>
      <%=render 'table'%>
    </table>
  </div>
</div>

<div id='calendar-modals'>
  <%=render 'modals'%>
</div>

app/views/calendars/show_period.js.erb
document.getElementById("calendar_table").innerHTML = "<%= escape_javascript(render 'table') %>";
document.getElementById("calendar-modals").innerHTML = "<%= escape_javascript(render 'modals') %>";
$('.modal-trigger').leanModal();
<% if @google_msg %>
  Materialize.toast('<%=@google_msg%>');
<% end%>